In [ ]:
#51 exercise
import numpy as np

data = [('position', ['x', 'y']), 
         ('color',    ['r',  'g', 'b'])]



[('position', ['x', 'y']), ('color', ['r', 'g', 'b'])]

In [ ]:
#52
from scipy.spatial import distance_matrix

points = np.random.rand(100, 2)
distances = distance_matrix(points, points)

print(distances)



[[0.         0.0197916  0.684786   ... 0.43194253 0.82179265 0.49290776]
 [0.0197916  0.         0.66795384 ... 0.4134152  0.81472633 0.48639344]
 [0.684786   0.66795384 0.         ... 0.27413035 0.49701908 0.4275485 ]
 ...
 [0.43194253 0.4134152  0.27413035 ... 0.         0.62431006 0.3916404 ]
 [0.82179265 0.81472633 0.49701908 ... 0.62431006 0.         0.32918132]
 [0.49290776 0.48639344 0.4275485  ... 0.3916404  0.32918132 0.        ]]


In [ ]:
#53
a=np.array(34,dtype=np.float32)
b=a.astype(np.int32)
print(b)

34


In [ ]:
#54
from io import StringIO

text = """1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11"""

data = np.genfromtxt(StringIO(text), delimiter=",", dtype=int)
print(data)


In [49]:
#55
arr = np.array([10, 20, 30, 40])
for index, value in np.ndenumerate(arr):
    print(index, value)


(0,) 10
(1,) 20
(2,) 30
(3,) 40


In [50]:
#56
import scipy.stats as st

def gaussian_2d(shape=(10,10), sigma=1):
    m, n = [(dim-1)/2 for dim in shape]
    y, x = np.ogrid[-m:m+1, -n:n+1]
    return np.exp(-(x**2 + y**2) / (2 * sigma**2))

gaussian = gaussian_2d()
print(gaussian)


[[1.60522806e-09 8.76424822e-08 1.76034631e-06 1.30072977e-05
  3.53575009e-05 3.53575009e-05 1.30072977e-05 1.76034631e-06
  8.76424822e-08 1.60522806e-09]
 [8.76424822e-08 4.78511739e-06 9.61116521e-05 7.10174389e-04
  1.93045414e-03 1.93045414e-03 7.10174389e-04 9.61116521e-05
  4.78511739e-06 8.76424822e-08]
 [1.76034631e-06 9.61116521e-05 1.93045414e-03 1.42642339e-02
  3.87742078e-02 3.87742078e-02 1.42642339e-02 1.93045414e-03
  9.61116521e-05 1.76034631e-06]
 [1.30072977e-05 7.10174389e-04 1.42642339e-02 1.05399225e-01
  2.86504797e-01 2.86504797e-01 1.05399225e-01 1.42642339e-02
  7.10174389e-04 1.30072977e-05]
 [3.53575009e-05 1.93045414e-03 3.87742078e-02 2.86504797e-01
  7.78800783e-01 7.78800783e-01 2.86504797e-01 3.87742078e-02
  1.93045414e-03 3.53575009e-05]
 [3.53575009e-05 1.93045414e-03 3.87742078e-02 2.86504797e-01
  7.78800783e-01 7.78800783e-01 2.86504797e-01 3.87742078e-02
  1.93045414e-03 3.53575009e-05]
 [1.30072977e-05 7.10174389e-04 1.42642339e-02 1.05399225e

In [64]:
#57 
array=np.zeros((10,10),dtype=int)
print(array)
p=10
indices = np.random.choice(arr.size, p)
arr.ravel()[indices]=1
print(arr)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[1 1 1 1]


In [71]:
#58
data=np.random.randint(1,10 ,size=(5,5))
for i in data :
    print(i.mean())
print(data)

4.4
4.2
5.0
6.0
6.0
[[6 1 4 6 5]
 [2 2 5 6 6]
 [3 5 1 9 7]
 [4 9 6 8 3]
 [7 6 8 5 4]]


In [82]:
#59
data=np.random.randint(1,10 ,size=(5,5))
n=4
sorted_data=data[data[:,n].argsort()]
print(sorted_data)

[[6 1 9 3 1]
 [1 9 7 2 6]
 [7 8 4 3 7]
 [4 9 7 7 8]
 [5 3 5 5 9]]


In [ ]:
#60
A = np.array([[1, 0, 3, 0, 5,6],
              [0, 0, 6, 0, 8,6],
              [9, 0, 3, 0, 2,7],
              [4, 0, 5, 0, 1,8],
              [7, 0, 2, 0, 6,9]])
null_columns=np.all(A==0,axis=1)
colums=np.any(null_columns)

print(null_columns)
print(colums)


[False False False False False]
False
5


In [101]:
#61
A = np.random.randint(1,100,size=10)
target=int(input('write the value which you want to find nearest value from the array'))

nearest_value = A[np.abs(A - target).argmin()]
print(A)
print(nearest_value)



[62 84 40 19 22 53 44 50 97 73]
19


In [1]:
#62
import numpy as np

In [33]:
a=np.array([[1,2,3]])
b=np.array([[1],[2],[3]])

it = np.nditer([a,b ,None]) 
for a, b, c in it:
    c[...] = a + b  
result = it.operands[2]
print(result)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [38]:
#2-exercise
import numpy as np

numbers=np.arange(1,11)

square_numbers=numbers**2
sum=square_numbers.sum()
mean=square_numbers.mean()
std=square_numbers.std()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

[np.int64(3), array([1, 2, 3])]
